C     EXECUTIVE.F  — Executive + Waitlist + Phase Table  (src/agc/executive.ts)
      BLOCK DATA EXECDT
      INTEGER NJOBS, NWAIT, ITIME
      INTEGER IJOBID, IPRIO, IPC, IVAC, IPHASQ, IWTIME, IWTJOB
      COMMON /EXEC/ NJOBS, IJOBID(8), IPRIO(8), IPC(8), IVAC(8),
     *              IPHASQ(8), NWAIT, IWTIME(20), IWTJOB(20), ITIME
      DATA NJOBS/0/, NWAIT/0/, ITIME/0/
      DATA IJOBID/8*0/, IPRIO/8*0/, IPC/8*0/, IVAC/8*0/, IPHASQ/8*0/
      DATA IWTIME/20*0/, IWTJOB/20*0/
      END
C     NOVAC — allocate VAC; sort by priority (0 highest)
      SUBROUTINE NOVAC(IPRI,IPCAD,IJOB,ISTAT)
      INTEGER IPRI, IPCAD, IJOB, ISTAT, I, J, ITMP
      INTEGER NJOBS, IJOBID, IPRIO, IPC, IVAC, IPHASQ, NWAIT
      INTEGER IWTIME, IWTJOB, ITIME
      COMMON /EXEC/ NJOBS, IJOBID(8), IPRIO(8), IPC(8), IVAC(8),
     *              IPHASQ(8), NWAIT, IWTIME(20), IWTJOB(20), ITIME
      ISTAT=0
      IF (NJOBS .GE. 8) THEN
         ISTAT=1202
         IJOB=-1
         RETURN
      ENDIF
      NJOBS=NJOBS+1
      IJOB=NJOBS
      IJOBID(NJOBS)=IJOB
      IPRIO(NJOBS)=IPRI
      IPC(NJOBS)=IPCAD
      IVAC(NJOBS)=NJOBS-1
      IPHASQ(NJOBS)=1
C     Simple insertion sort by IPRIO ascending (0 highest)
      DO 20 I=NJOBS,2,-1
        IF (IPRIO(I).LT.IPRIO(I-1)) THEN
          ITMP=IJOBID(I); IJOBID(I)=IJOBID(I-1); IJOBID(I-1)=ITMP
          ITMP=IPRIO(I); IPRIO(I)=IPRIO(I-1); IPRIO(I-1)=ITMP
          ITMP=IPC(I); IPC(I)=IPC(I-1); IPC(I-1)=ITMP
          ITMP=IVAC(I); IVAC(I)=IVAC(I-1); IVAC(I-1)=ITMP
          ITMP=IPHASQ(I); IPHASQ(I)=IPHASQ(I-1); IPHASQ(I-1)=ITMP
        ENDIF
 20   CONTINUE
      RETURN
      END
      SUBROUTINE ENDJOB(IJID)
      INTEGER IJID, I, J, NJOBS, IJOBID, IPRIO, IPC, IVAC
      INTEGER IPHASQ, NWAIT, IWTIME, IWTJOB, ITIME
      COMMON /EXEC/ NJOBS, IJOBID(8), IPRIO(8), IPC(8), IVAC(8),
     *              IPHASQ(8), NWAIT, IWTIME(20), IWTJOB(20), ITIME
      DO 30 I=1,NJOBS
        IF (IJOBID(I).EQ.IJID) THEN
          DO 25 J=I,NJOBS-1
            IJOBID(J)=IJOBID(J+1); IPRIO(J)=IPRIO(J+1)
            IPC(J)=IPC(J+1); IVAC(J)=IVAC(J+1); IPHASQ(J)=IPHASQ(J+1)
 25       CONTINUE
          NJOBS=NJOBS-1
          RETURN
        ENDIF
 30   CONTINUE
      RETURN
      END
      SUBROUTINE LONGCL(IDLY,IJOB)
      INTEGER IDLY, IJOB, I, NJOBS, IJOBID, IPRIO, IPC, IVAC
      INTEGER IPHASQ, NWAIT, IWTIME, IWTJOB, ITIME, IT
      COMMON /EXEC/ NJOBS, IJOBID(8), IPRIO(8), IPC(8), IVAC(8),
     *              IPHASQ(8), NWAIT, IWTIME(20), IWTJOB(20), ITIME
      IF (NWAIT .GE. 20) RETURN
      IT = ITIME + IDLY
      NWAIT = NWAIT + 1
      IWTIME(NWAIT)=IT
      IWTJOB(NWAIT)=IJOB
C     insertion sort by time
      DO 40 I=NWAIT,2,-1
        IF (IWTIME(I).LT.IWTIME(I-1)) THEN
          IT=IWTIME(I); IWTIME(I)=IWTIME(I-1); IWTIME(I-1)=IT
          IT=IWTJOB(I); IWTJOB(I)=IWTJOB(I-1); IWTJOB(I-1)=IT
        ENDIF
 40   CONTINUE
      RETURN
      END
      SUBROUTINE EXECTK(IDT)
      INTEGER IDT, I, J, NJOBS, IJOBID, IPRIO, IPC, IVAC, IPHASQ
      INTEGER NWAIT, IWTIME, IWTJOB, ITIME, IDUM, ISTAT
      COMMON /EXEC/ NJOBS, IJOBID(8), IPRIO(8), IPC(8), IVAC(8),
     *              IPHASQ(8), NWAIT, IWTIME(20), IWTJOB(20), ITIME
      ITIME = ITIME + IDT
 50   IF (NWAIT.GT.0 .AND. IWTIME(1).LE.ITIME) THEN
        CALL NOVAC(6, IWTJOB(1), IDUM, ISTAT)
        DO 55 I=1,NWAIT-1
          IWTIME(I)=IWTIME(I+1); IWTJOB(I)=IWTJOB(I+1)
 55     CONTINUE
        NWAIT=NWAIT-1
        GOTO 50
      ENDIF
      RETURN
      END
      SUBROUTINE SETPHA(IJID,IPH)
      INTEGER IJID, IPH, I, NJOBS, IJOBID, IPRIO, IPC, IVAC, IPHASQ
      INTEGER NWAIT, IWTIME, IWTJOB, ITIME
      COMMON /EXEC/ NJOBS, IJOBID(8), IPRIO(8), IPC(8), IVAC(8),
     *              IPHASQ(8), NWAIT, IWTIME(20), IWTJOB(20), ITIME
      DO 60 I=1,NJOBS
        IF (IJOBID(I).EQ.IJID) IPHASQ(I)=IPH
 60   CONTINUE
      RETURN
      END
