C     FAULT.F  — Fault Injector  (src/replay/fault.ts)
C     IKIND: 0=1202,1=1201,2=COM_DROP,3=DPS_STUCK,4=IMU_DRIFT
      SUBROUTINE FLTINS(IKIND, IMET, AMAG, IERR)
      INTEGER IKIND, IMET, IERR, I, IDUM, ISTAT
      REAL*8 AMAG, THRUST, ISP, THROTT, POS, VEL, AMASS, AMDRY, CDU
      INTEGER IMETSC, IMETH, IVEH, IGUID, IENG, IENGON, ICOMM
      INTEGER IALARM, IPHASE, NJOBS, IJOBID, IPRIO, IPC, IVAC
      INTEGER IPHASQ, NWAIT, IWTIME, IWTJOB, ITIME
      CHARACTER*9 CMET
      COMMON /MSTATE/ IMETSC, IMETH(3), IVEH, IGUID, IENG, THRUST,
     *                ISP, THROTT, IENGON, ICOMM, POS(3), VEL(3),
     *                AMASS, AMDRY, CDU(3), IALARM, IPHASE(8)
      COMMON /EXEC/ NJOBS, IJOBID(8), IPRIO(8), IPC(8), IVAC(8),
     *              IPHASQ(8), NWAIT, IWTIME(20), IWTJOB(20), ITIME
      COMMON /MSTATC/ CMET
      IERR=0
      IF (IKIND.EQ.0) THEN
C        1202 — flood EXEC at given MET (DOCUMENTED PDI)
         DO 10 I=1,10
           CALL NOVAC(6, 2048+I, IDUM, ISTAT)
           IF (ISTAT.EQ.1202) THEN
              IALARM=1202
              GOTO 20
           ENDIF
 10      CONTINUE
      ELSE IF (IKIND.EQ.2) THEN
         ICOMM=3
      ELSE IF (IKIND.EQ.3) THEN
         THROTT = AMAG
      ELSE IF (IKIND.EQ.4) THEN
         CDU(1)=CDU(1)+AMAG
      ENDIF
 20   RETURN
      END
