C     PROPULSION.F  — Engines, throttle, massFlow  (src/physics/propulsion.ts)
      BLOCK DATA ENGDTA
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      REAL*8 THRMAX, ISPV, THRMIN, THRMAXF
      COMMON /ENGTAB/ THRMAX(5), ISPV(5), THRMIN(5), THRMAXF(5)
C     Order: 1 DPS, 2 APS, 3 SPS, 4 F-1, 5 J-2
      DATA THRMAX/45000.D0,15500.D0,91190.D0,6.77D6,1.033D6/
      DATA ISPV/311.D0,311.D0,314.D0,263.D0,421.D0/
      DATA THRMIN/0.10D0,1.D0,1.D0,1.D0,1.D0/
      DATA THRMAXF/0.94D0,1.D0,1.D0,1.D0,1.D0/
      END
C     THROTC — DOCUMENTED THROTTLE_CONTROL 793-797
      REAL*8 FUNCTION THROTC(ACMD, FC, AMASS)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      REAL*8 ACMD, FC, AMASS, FCEFF, THRMAX, ISPV, THRMIN, THRMAXF
      COMMON /ENGTAB/ THRMAX(5), ISPV(5), THRMIN(5), THRMAXF(5)
      IF (FC .EQ. 0.D0) THEN
         FCEFF = THRMAX(1)/AMASS
      ELSE
         FCEFF = FC
      ENDIF
      IF (FCEFF .EQ. 0.D0) THEN
         THROTC = THRMIN(1)
         RETURN
      ENDIF
      THROTC = DABS(ACMD)/FCEFF
      IF (THROTC .LT. THRMIN(1)) THROTC = THRMIN(1)
      IF (THROTC .GT. THRMAXF(1)) THROTC = THRMAXF(1)
      RETURN
      END
      REAL*8 FUNCTION MASSFL(THRUST, ISP)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      REAL*8 THRUST, ISP, G0
      PARAMETER (G0=9.80665D0)
      MASSFL = THRUST/(ISP*G0)
      RETURN
      END
