C     REPLAY.F  — Deterministic Replay  (src/replay/deterministic.ts)
      BLOCK DATA REPDTA
      INTEGER CURSOR, NHASH, ICHASH
      COMMON /REPLAY/ CURSOR, NHASH, ICHASH
      DATA CURSOR/0/, NHASH/0/, ICHASH/0/
      END
      SUBROUTINE REPINI
      INTEGER CURSOR, NHASH, ICHASH
      COMMON /REPLAY/ CURSOR, NHASH, ICHASH
      CURSOR=0; NHASH=0; ICHASH=0
      CALL TELINI
      RETURN
      END
      INTEGER FUNCTION ICHASHF(IPREV, IMETSC, AMASS)
      INTEGER IPREV, IMETSC, IMOD
      REAL*8 AMASS
      PARAMETER (IMOD=1000000007)
      ICHASHF = MOD(IPREV*31 + IMETSC + INT(AMASS), IMOD)
      RETURN
      END
C     REPSTP — step one event: EVTOST → canonical checksum
      SUBROUTINE REPSTP(IFRAME, IERR)
      INTEGER IFRAME, IERR, NEVENT, IMETEV, IVEHEV, IGUIDV, ICOMMV
      INTEGER IALRMV, CURSOR, NHASH, ICHASH, IMETSC, IMETH
      INTEGER IVEH, IGUID, IENG, IENGON, ICOMM, IALARM, IPHASE, ICHASHF
      REAL*8 POS, VEL, AMASS, AMDRY, CDU, THRUST, ISP, THROTT
      CHARACTER*9 CMET, CMETEV
      CHARACTER*40 CEVENT
      COMMON /TIMELN/ NEVENT, IMETEV(22), IVEHEV(22), IGUIDV(22),
     *                ICOMMV(22), IALRMV(22)
      COMMON /TIMECT/ CMETEV(22), CEVENT(22)
      COMMON /MSTATE/ IMETSC, IMETH(3), IVEH, IGUID, IENG, THRUST,
     *                ISP, THROTT, IENGON, ICOMM, POS(3), VEL(3),
     *                AMASS, AMDRY, CDU(3), IALARM, IPHASE(8)
      COMMON /MSTATC/ CMET
      COMMON /REPLAY/ CURSOR, NHASH, ICHASH
      IERR=0
      IF (CURSOR .GE. NEVENT) THEN
         IERR=1
         RETURN
      ENDIF
      CALL EVTOST(CURSOR+1)
      ICHASH = ICHASHF(ICHASH, IMETSC, AMASS)
      NHASH = ICHASH
      IFRAME = CURSOR+1
      CURSOR = CURSOR + 1
      RETURN
      END
C     REPRUN — run all 22
      SUBROUTINE REPRUN(N, IERR)
      INTEGER N, IERR, IFRAME, I
      INTEGER NEVENT, IMETEV, IVEHEV, IGUIDV, ICOMMV, IALRMV
      COMMON /TIMELN/ NEVENT, IMETEV(22), IVEHEV(22), IGUIDV(22),
     *                ICOMMV(22), IALRMV(22)
      N=0; IERR=0
      DO 100 I=1,NEVENT
        CALL REPSTP(IFRAME, IERR)
        IF (IERR.NE.0) RETURN
        N=N+1
 100  CONTINUE
      RETURN
      END
C     REPVFY — verify determinism: run twice, compare final hash
      SUBROUTINE REPVFY(IMATCH)
      INTEGER IMATCH, N, IERR, IH1, IH2, CURSOR, NHASH, ICHASH
      COMMON /REPLAY/ CURSOR, NHASH, ICHASH
      CALL REPINI
      CALL REPRUN(N, IERR); IH1=ICHASH
      CALL REPINI
      CALL REPRUN(N, IERR); IH2=ICHASH
      IF (IH1.EQ.IH2) THEN
         IMATCH=1
      ELSE
         IMATCH=0
      ENDIF
      RETURN
      END
C     WRSTATE — write 80-col record per 04 spec
      SUBROUTINE WRSTATE(IUNIT, IERR)
      INTEGER IUNIT, IERR, IMETSC, IMETH, IVEH, IGUID, IENG
      INTEGER IENGON, ICOMM, IALARM, IPHASE, ICHKSUM, ILISTI, NWORDS
      REAL*8 POS, VEL, AMASS, AMDRY, CDU, THRUST, ISP, THROTT
      CHARACTER*9 CMET
      COMMON /MSTATE/ IMETSC, IMETH(3), IVEH, IGUID, IENG, THRUST,
     *                ISP, THROTT, IENGON, ICOMM, POS(3), VEL(3),
     *                AMASS, AMDRY, CDU(3), IALARM, IPHASE(8)
      COMMON /MSTATC/ CMET
      COMMON /TELEM/ ICHKSUM, ILISTI, NWORDS
      IERR=0
      WRITE(IUNIT,'(A9,1X,I8,1X,I4,1X,I4,1X,F8.2,1X,I8,1X,3F7.1,1X,3F6.1,
     *1X,I2)', ERR=90) CMET, IMETSC, IVEH, IGUID, THROTT*1000.D0,
     *IALARM, POS(1)/1000.D0, POS(2)/1000.D0, POS(3)/1000.D0,
     *VEL(1), VEL(2), VEL(3), ICOMM
      RETURN
 90   IERR=1
      RETURN
      END
      SUBROUTINE WRSUMM(IUNIT)
      INTEGER IUNIT, CURSOR, NHASH, ICHASH
      REAL*8 POS, VEL, AMASS, AMDRY, CDU, THRUST, ISP, THROTT
      INTEGER IMETSC, IMETH, IVEH, IGUID, IENG, IENGON, ICOMM
      INTEGER IALARM, IPHASE
      CHARACTER*9 CMET
      COMMON /MSTATE/ IMETSC, IMETH(3), IVEH, IGUID, IENG, THRUST,
     *                ISP, THROTT, IENGON, ICOMM, POS(3), VEL(3),
     *                AMASS, AMDRY, CDU(3), IALARM, IPHASE(8)
      COMMON /MSTATC/ CMET
      COMMON /REPLAY/ CURSOR, NHASH, ICHASH
      WRITE(IUNIT,'(A5,I10,A4,I4,A11,3F7.1)') 'CHK= ',ICHASH,
     *' N=',CURSOR,' FINAL POS',POS(1),POS(2),POS(3)
      RETURN
      END
