C     TELEMETRY.F  — build frames, checksum  (src/telemetry/downlink.ts)
      BLOCK DATA TELDTA
      INTEGER ICHKSUM, ILISTI, NWORDS
      COMMON /TELEM/ ICHKSUM, ILISTI, NWORDS
      DATA ICHKSUM/0/, ILISTI/0/, NWORDS/0/
      END
      SUBROUTINE TELINI
      INTEGER ICHKSUM, ILISTI, NWORDS
      COMMON /TELEM/ ICHKSUM, ILISTI, NWORDS
      ICHKSUM=0
      RETURN
      END
      INTEGER FUNCTION ICHFNC(IPREV, IMETSC, AMASS)
      INTEGER IPREV, IMETSC, IMOD
      REAL*8 AMASS
      PARAMETER (IMOD=1000000007)
      ICHFNC = MOD(IPREV*31 + IMETSC + INT(AMASS), IMOD)
      RETURN
      END
C     BFRAME — build telemetry frame (replaces SHA256 hash chain)
C     Updates ICHKSUM via ICHFNC; sets ILISTID based on IGUID
      SUBROUTINE BFRAME(IMETSC, IGUID, NWD, IERR)
      INTEGER IMETSC, IGUID, NWD, IERR, ICHKSUM, ILISTI, NWORDS
      INTEGER ICHFNC, IMOD
      REAL*8 AMASS, AMDRY, POS, VEL, CDU, THRUST, ISP, THROTT
      INTEGER IMETH, IVEH, IENG, IENGON, ICOMM, IALARM, IPHASE
      CHARACTER*8 CMET
      COMMON /MSTATE/ IMETSC_G, IMETH(3), IVEH, IGUID_G, IENG, THRUST,
     *                ISP, THROTT, IENGON, ICOMM, POS(3), VEL(3),
     *                AMASS, AMDRY, CDU(3), IALARM, IPHASE(8)
      COMMON /MSTATC/ CMET
      COMMON /TELEM/ ICHKSUM, ILISTI, NWORDS
      PARAMETER (IMOD=1000000007)
      IERR=0
      IF (IGUID.EQ.63 .OR. IGUID.EQ.64) THEN
         ILISTI=2
      ELSE
         ILISTI=0
      ENDIF
      NWORDS=2
      NWD=NWORDS
      ICHKSUM = ICHFNC(ICHKSUM, IMETSC, AMASS)
      RETURN
      END
