C     TIMELINE.F  — Load 22-event dataset  (src/mission/timeline.ts)
      BLOCK DATA TIMDTA
      INTEGER NEVENT, IMETEV, IVEHEV, IGUIDV, ICOMMV, IALRMV
      CHARACTER*9 CMETEV
      CHARACTER*40 CEVENT
      COMMON /TIMELN/ NEVENT, IMETEV(22), IVEHEV(22), IGUIDV(22),
     *                ICOMMV(22), IALRMV(22)
      COMMON /TIMECT/ CMETEV(22), CEVENT(22)
      DATA NEVENT/0/
      DATA IMETEV/22*0/, IVEHEV/22*0/, IGUIDV/22*0/
      DATA ICOMMV/22*0/, IALRMV/22*0/
      END
C     LDTIML — LOAD TIMELINE (replaces JSON loadTimeline)
C     FNAME = file, NEVENT returned, IERR 0 ok
      SUBROUTINE LDTIML(FNAME, NERR)
      CHARACTER*(*) FNAME
      INTEGER NERR, NEVENT, IMETEV, IVEHEV, IGUIDV, ICOMMV, IALRMV
      CHARACTER*9 CMETEV
      CHARACTER*40 CEVENT
      COMMON /TIMELN/ NEVENT, IMETEV(22), IVEHEV(22), IGUIDV(22),
     *                ICOMMV(22), IALRMV(22)
      COMMON /TIMECT/ CMETEV(22), CEVENT(22)
      INTEGER I, IH, IM, IS, IV, IG, IC, IA
      CHARACTER*9 CM
      NERR=0
      OPEN(UNIT=10, FILE=FNAME, STATUS='OLD', ERR=90)
      READ(10,*, ERR=91) NEVENT
      IF (NEVENT .GT. 22) NEVENT=22
      DO 10 I=1,NEVENT
C       List-directed for portability (A9 format fragile on Windows)
         READ(10,*, ERR=91) CM, IMETEV(I), IVEHEV(I), IGUIDV(I),
     *        IALRMV(I), ICOMMV(I)
         CMETEV(I)=CM
         CEVENT(I)=' '
 10   CONTINUE
      CLOSE(10)
      RETURN
 90   WRITE(6,*) 'LDTIML OPEN ERR FNAME=',FNAME
      NERR=1
      RETURN
 91   WRITE(6,*) 'LDTIML READ ERR FNAME=',FNAME,' I=',I
      NERR=1
      CLOSE(10)
      RETURN
      END
C     EVTOST — eventsToStates: populate COMMON /MSTATE/ from event I
      SUBROUTINE EVTOST(I)
      INTEGER I, NEVENT, IMETEV, IVEHEV, IGUIDV, ICOMMV, IALRMV
      CHARACTER*9 CMETEV
      CHARACTER*40 CEVENT
      COMMON /TIMELN/ NEVENT, IMETEV(22), IVEHEV(22), IGUIDV(22),
     *                ICOMMV(22), IALRMV(22)
      COMMON /TIMECT/ CMETEV(22), CEVENT(22)
      INTEGER IMETSC, IMETH, IVEH, IGUID, IENG, IENGON, ICOMM
      INTEGER IALARM, IPHASE
      REAL*8 POS, VEL, AMASS, AMDRY, CDU, THRUST, ISP, THROTT
      CHARACTER*9 CMET
      COMMON /MSTATE/ IMETSC, IMETH(3), IVEH, IGUID, IENG, THRUST,
     *                ISP, THROTT, IENGON, ICOMM, POS(3), VEL(3),
     *                AMASS, AMDRY, CDU(3), IALARM, IPHASE(8)
      COMMON /MSTATC/ CMET
      IMETSC = IMETEV(I)
      CALL ITOMET(IMETSC, IMETH(1), IMETH(2), IMETH(3))
      CMET = CMETEV(I)
      IVEH = IVEHEV(I)
      IGUID = IGUIDV(I)
      IALARM = IALRMV(I)
      ICOMM = ICOMMV(I)
C     Defaults preserved from TS eventsToStates
      POS(1)=0.D0; POS(2)=0.D0; POS(3)=0.D0
      VEL(1)=0.D0; VEL(2)=0.D0; VEL(3)=0.D0
      AMASS=15000.D0; AMDRY=4000.D0
      CDU(1)=0.D0; CDU(2)=0.D0; CDU(3)=0.D0
      THRUST=0.D0; ISP=311.D0; THROTT=0.D0; IENGON=0
      RETURN
      END
